machine:
  id: 1000

server:
  port: 8083

external:
  bank:
    host: localhost
    port: 6061
  zaloWallet:
    host: localhost
    port: 6060
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3306/payment_engine
    username: root
    password:
